export const GET_LIST_FRIEND = 'GET_LIST_FRIEND'
export const GET_LIST_FRIEND_SEARCH = 'GET_LIST_FRIEND_SEARCH'
export const GET_MESSAGE_OF_LIST_FRIEND = 'GET_MESSAGE_OF_LIST_FRIEND'
export const RESET_LIST_FRIEND = 'RESET_LIST_FRIEND'


